books:
  merchant_balance: 1
  merchant_withholding_balance: 2
  merchant_credit: 3
  given_balance: 21
  given_credit: 22
  settlement: 41
  settlement_fee: 42
  subscription: 51
  boleto: 101
  boleto_fee: 102
  boleto_refund: 103
  cc: 121
  cc_fee: 122
  cc_refund: 123
  cc_refund_fee: 124
  cc_chargeback: 125
  cc_chargeback_fee: 126
  cc_anticipation: 127
  cc_anticipation_fee: 128

txs:
  balance:
    code: 10
    book_add: merchant_balance
    book_sub: given_credit
  credit:
    code: 11
    book_add: merchant_credit
    book_sub: given_credit
  settlement:
    code: 12
    book_add: settlement
    book_sub: merchant_balance
  settlement_fee:
    code: 13
    book_add: settlement_fee
    book_sub: merchant_balance
  subscription:
    code: 14
    book_add: subscription
    book_sub: merchant_balance
  boleto_payment:
    code: 15
    book_add: merchant_balance
    book_sub: boleto
  boleto_fee:
    code: 16
    book_add: boleto_fee
    book_sub: merchant_balance
  boleto_refund:
    code: 17
    book_add: boleto_refund
    book_sub: merchant_balance
  cc:
    code: 18
    book_add: merchant_withholding_balance
    book_sub: cc
  cc_fee:
    code: 19
    book_add: cc_fee
    book_sub: merchant_balance
  cc_refund:
    code: 20
    book_add: cc_refund
    book_sub: merchant_balance
  cc_refund_fee:
    code: 21
    book_add: cc_refund_fee
    book_sub: merchant_balance
  cc_chargeback:
    code: 22
    book_add: cc_chargeback
    book_sub: merchant_balance
  cc_chargeback_fee:
    code: 23
    book_add: cc_chargeback_fee
    book_sub: merchant_balance
  cc_anticipation:
    code: 24
    book_add: cc_anticipation
    book_sub: merchant_balance
  cc_anticipation_fee:
    code: 25
    book_add: cc_anticipation_fee
    book_sub: merchant_balance
