operations: psp

#
# Accounting books
#
books:
  # Merchant
  merchant_balance: 9000001
  merchant_adjusted: 9000002
  merchant_withholding: 9000003
  merchant_locked: 9000004

  # Partner
  partner_balance: 8000001
  partner_adjusted: 8000002
  partner_withholding: 8000003
  partner_locked: 8000004

  # Customer
  customer_balance: 7000001
  customer_adjusted: 7000002
  customer_withholding: 7000003
  customer_locked: 7000004

  # Payment Processing: PSP, gateway
  pp_payment: 1000001

  pp_charge_direct: 1110001
  pp_charge_bank_transfer: 1110002
  pp_charge_credit_card: 1110003
  pp_charge_debit_card: 1110004
  pp_charge_wallet: 1110005
  pp_charge_pix: 1110006

  pp_charge_direct_fee: 1120001
  pp_charge_bank_transfer_fee: 1120002
  pp_charge_credit_card_fee: 1120003
  pp_charge_debit_card_fee: 1120004
  pp_charge_wallet_fee: 1120005
  pp_charge_pix_fee: 1120006

  pp_refund: 1210001
  pp_refund_fee: 1220001

  pp_chargeback: 1310001
  pp_chargeback_fee: 1320001

  # Withdrawals
  wdw: 2000001
  wdw_merchant: 2100011
  wdw_merchant_requested: 2100012
  wdw_partner: 2100021
  wdw_partner_requested: 2100022
  wdw_customer: 2100031
  wdw_customer_requested: 2100032

entry_pairs:
  balance:
    code: 1000
    book_add: merchant_balance
    book_sub: given_credit
  credit:
    code: 2000
    book_add: merchant_credit
    book_sub: given_credit
  settlement_processing:
    code: 4000
    book_add: settlement_processing
    book_sub: merchant_balance
  settlement:
    code: 4001
    book_add: settlement
    book_sub: settlement_processing
  settlement_fee:
    code: 4002
    book_add: settlement_fee
    book_sub: merchant_balance
  subscription:
    code: 5000
    book_add: subscription
    book_sub: merchant_balance
  boleto_payment:
    code: 11000
    book_add: merchant_balance
    book_sub: boleto
  boleto_fee:
    code: 11001
    book_add: boleto_fee
    book_sub: merchant_balance
  boleto_refund_processing:
    code: 11002
    book_add: boleto_refund_processing
    book_sub: merchant_balance
  boleto_refund:
    code: 11003
    book_add: boleto_refund
    book_sub: boleto_refund_processing
  pix_payment:
    code: 12000
    book_add: merchant_balance
    book_sub: pix
  pix_fee:
    code: 12001
    book_add: pix_fee
    book_sub: merchant_balance
  pix_refund_processing:
    code: 12002
    book_add: pix_refund_processing
    book_sub: merchant_balance
  pix_refund:
    code: 12003
    book_add: pix_refund
    book_sub: pix_refund_processing
  cc:
    code: 13000
    book_add: merchant_withholding_balance
    book_sub: cc
  cc_fee:
    code: 13011
    book_add: cc_fee
    book_sub: merchant_balance
  cc_refund:
    code: 13021
    book_add: cc_refund
    book_sub: merchant_balance
  cc_refund_fee:
    code: 13031
    book_add: cc_refund_fee
    book_sub: merchant_balance
  cc_chargeback:
    code: 13041
    book_add: cc_chargeback
    book_sub: merchant_balance
  cc_chargeback_fee:
    code: 13051
    book_add: cc_chargeback_fee
    book_sub: merchant_balance
  cc_anticipation:
    code: 13061
    book_add: cc_anticipation
    book_sub: merchant_balance
  cc_anticipation_fee:
    code: 13071
    book_add: cc_anticipation_fee
    book_sub: merchant_balance
