operations: general

#
# Accounting books
#
books:
  # Merchant
  - merchant_available
  - merchant_withheld
  - merchant_pending
  - merchant_locked
  - merchant_adjusted
  - merchant_credit:
      non_negative: true

  # Partner
  - partner_available
  - partner_withheld
  - partner_pending
  - partner_locked
  - partner_adjusted
  - partner_credit:
      non_negative: true

  # Customer
  - customer_available
  - customer_withheld
  - customer_pending
  - customer_locked
  - customer_adjusted
  - customer_credit:
      non_negative: true
  
  # Withdrawals
  - wdw
  - wdw_request
  - wdw_merchant
  - wdw_merchant_request
  - wdw_partner
  - wdw_partner_request
  - wdw_customer
  - wdw_customer_request

  # Payment Processing: PSP, gateway
  - payment_bank_transfer
  - payment_credit_card
  - payment_wallet
  - payment_pix

  - charge_bank_transfer
  - charge_credit_card
  - charge_wallet
  - charge_pix

  - charge_fee_merchant
  - charge_fee_partner
  - charge_fee_customer

#
# Entry pairs.
#
entry_pairs:
  # Payments
  charge_pix_payment:
    book_sub: charge_pix
    book_add: payment_pix

  # Splits
  split_merchant:
    book_sub: payment
    book_add: merchant_withholding
  split_partner:
    book_sub: payment
    book_add: partner_withholding
