operations: psp

#
# Accounting books
#
books:
  # Merchant
  merchant_balance: 9000001
  merchant_adjusted: 9000002
  merchant_withholding: 9000003
  merchant_locked: 9000004

  # Partner
  partner_balance: 8000001
  partner_adjusted: 8000002
  partner_withholding: 8000003
  partner_locked: 8000004

  # Customer
  customer_balance: 7000001
  customer_adjusted: 7000002
  customer_withholding: 7000003
  customer_locked: 7000004

  # Payment Processing: PSP, gateway
  pp_payment: 1000001

  pp_charge_direct: 1110001
  pp_charge_bank_transfer: 1110002
  pp_charge_credit_card: 1110003
  pp_charge_debit_card: 1110004
  pp_charge_wallet: 1110005
  pp_charge_pix: 1110006

  pp_charge_direct_fee: 1120001
  pp_charge_bank_transfer_fee: 1120002
  pp_charge_credit_card_fee: 1120003
  pp_charge_debit_card_fee: 1120004
  pp_charge_wallet_fee: 1120005
  pp_charge_pix_fee: 1120006

  pp_refund: 1210001
  pp_refund_fee: 1220001

  pp_chargeback: 1310001
  pp_chargeback_fee: 1320001

  # Withdrawals
  wdw: 2000001
  wdw_merchant: 2100011
  wdw_merchant_requested: 2100012
  wdw_partner: 2100021
  wdw_partner_requested: 2100022
  wdw_customer: 2100031
  wdw_customer_requested: 2100032

entry_pairs:
  withheld_balance:
    code: 1000
    book_add: merchant_balance
    book_sub: given_credit
