module Stern
  InvalidTime = Class.new(StandardError)
  InvalidDate = Class.new(StandardError)
  ShouldBeDateOrTimestamp = Class.new(StandardError)
  TimestampShouldBeDateTime = Class.new(StandardError)
  DateNotSpecified = Class.new(StandardError)
  CreditTxIdSeqInvalid = Class.new(StandardError)

  InvalidTxCode = Class.new(StandardError)
  InvalidTxName = Class.new(StandardError)
  InconsistentDefinitions = Class.new(StandardError)
  InvalidBook = Class.new(StandardError)
  BookDoesNotExist = Class.new(StandardError)
  OperationDoesNotExist = Class.new(StandardError)
  AmountShouldNotBeZero = Class.new(StandardError)
  CascadeShouldBeBoolean = Class.new(StandardError)
  AtomicShouldBeBoolean = Class.new(StandardError)
  InvalidGroupingDatePrecision = Class.new(StandardError)
  GidNotSpecified = Class.new(StandardError)
end
