module Stern
  InvalidTime = class.new(StandardError)
  InvalidDate = class.new(StandardError)
  ShouldBeDateOrTimestamp = class.new(StandardError)
  TimestampShouldBeDateTime = class.new(StandardError)
  DateNotSpecified = class.new(StandardError)
  CreditTxIdSeqInvalid = class.new(StandardError)

  InvalidTxCode = class.new(StandardError)
  InvalidTxName = class.new(StandardError)
  InconsistentDefinitions = class.new(StandardError)
  InvalidBook = class.new(StandardError)
  BookDoesNotExist = class.new(StandardError)
  OperationDoesNotExist = class.new(StandardError)
  AmountShouldNotBeZero = class.new(StandardError)
  CascadeShouldBeBoolean = class.new(StandardError)
  AtomicShouldBeBoolean = class.new(StandardError)
  InvalidGroupingDatePrecision = class.new(StandardError)
  GidNotSpecified = class.new(StandardError)
end
